# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-12 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0006_auto_20180301_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_socios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obraSocial', models.CharField(default='Sin Definir', max_length=30, null=True)),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Pendiente', 'Pendiente'), ('Desactivado', 'Desactivado')], default='Pendiente', max_length=30)),
                ('TarifaMensual', models.CharField(default='0000000', max_length=30, null=True)),
                ('dateCreate_socio', models.DateField(auto_now=True)),
                ('perfil', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='UserProfile.tb_profile')),
            ],
            options={
                'db_table': 'socios',
                'managed': True,
            },
        ),
    ]
