# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-12 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tb_socios',
            new_name='tb_socio',
        ),
    ]
