# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-12 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0002_auto_20180312_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_socio',
            name='TarifaMensual',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Configuracion.tb_plan'),
        ),
    ]
