# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-13 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0003_auto_20180312_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_socio',
            name='dateInactive_socio',
            field=models.DateField(default='1995-04-19', null=True),
        ),
    ]
