# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-07 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0004_tb_socio_dateinactive_socio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_socio',
            name='dateInactive_socio',
            field=models.DateField(default='2018-04-19', null=True),
        ),
    ]
