# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-15 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_ingreso_mensualidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(default='0000', null=True)),
                ('descripcion', models.TextField(default='', max_length=3000, null=True)),
                ('dateCreate', models.DateField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Configuracion.tb_plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
