# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-15 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tb_ingreso_mensualidad',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='tb_ingreso_mensualidad',
            table='ingreso_mensualidad',
        ),
    ]
