# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-15 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0002_auto_20180315_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_ingreso_mensualidad',
            name='apellido',
            field=models.CharField(default='Sin Apellido', max_length=300),
        ),
        migrations.AddField(
            model_name='tb_ingreso_mensualidad',
            name='correo',
            field=models.EmailField(default='sin@email.com', max_length=30),
        ),
        migrations.AddField(
            model_name='tb_ingreso_mensualidad',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=300),
        ),
        migrations.AlterField(
            model_name='tb_ingreso_mensualidad',
            name='descripcion',
            field=models.TextField(default='Sin Descripcion', max_length=3000, null=True),
        ),
    ]
