# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-15 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0005_tb_egreso_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_egreso',
            name='monto',
            field=models.FloatField(default='0000', null=True),
        ),
        migrations.AlterField(
            model_name='tb_ingreso_mensualidad',
            name='monto',
            field=models.FloatField(default='0000', null=True),
        ),
    ]
