# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-06 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0006_tb_tipoingreso'),
        ('Proveedores', '0001_initial'),
        ('Colaboradores', '0010_tb_colaboradores_ispresentimopay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Caja', '0006_auto_20180615_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_ingresos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(default='0000', null=True)),
                ('descripcion', models.TextField(default='Sin Descripcion', max_length=3000, null=True)),
                ('dateCreate', models.DateField(auto_now=True)),
                ('colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Colaboradores.tb_colaboradores')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedores.tb_proveedor')),
                ('tipoDeIngresos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Configuracion.tb_tipoIngreso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ingresos',
                'managed': True,
            },
        ),
    ]
