# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-06 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0007_tb_ingresos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_ingresos',
            name='colaborador',
        ),
        migrations.RemoveField(
            model_name='tb_ingresos',
            name='proveedor',
        ),
    ]
