# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-14 00:07
from __future__ import unicode_literals

import apps.Caja.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Caja', '0008_auto_20180706_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_cierre_de_caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(default=apps.Caja.models.get_default_my_hour, max_length=50)),
                ('dateCreate', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_cierre_de_caja',
                'managed': True,
            },
        ),
    ]
