# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-14 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0009_tb_cierre_de_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_cierre_de_caja',
            name='balanceGeneral',
            field=models.FloatField(default='0000', null=True),
        ),
        migrations.AddField(
            model_name='tb_cierre_de_caja',
            name='totalEgresos',
            field=models.FloatField(default='0000', null=True),
        ),
        migrations.AddField(
            model_name='tb_cierre_de_caja',
            name='totalIngresos',
            field=models.FloatField(default='0000', null=True),
        ),
    ]
