# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-14 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0010_auto_20180814_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_cierre_de_caja',
            name='egresos',
            field=models.TextField(default='Sin Descripcion', max_length=300000000, null=True),
        ),
        migrations.AddField(
            model_name='tb_cierre_de_caja',
            name='ingresos',
            field=models.TextField(default='Sin Descripcion', max_length=300000000, null=True),
        ),
        migrations.AddField(
            model_name='tb_cierre_de_caja',
            name='ingresos_mensualidades',
            field=models.TextField(default='Sin Descripcion', max_length=300000000, null=True),
        ),
    ]
