# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-12 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePlan', models.CharField(default='Sin Nonbre', max_length=30, null=True)),
                ('precioPlan', models.CharField(default='000000', max_length=30, null=True)),
                ('descripcionPlan', models.TextField(default='Sin Datos', null=True)),
                ('dateCreate', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planes',
                'managed': True,
            },
        ),
    ]
