# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-28 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_plan',
            name='precioPlanAnual',
            field=models.CharField(default='000000', max_length=30, null=True),
        ),
    ]
