# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-28 16:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Configuracion', '0002_tb_plan_precioplananual'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_formasDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFormasDePago', models.CharField(default='', max_length=30, unique=True)),
                ('dateCreate', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'formas_de_pago',
                'managed': True,
            },
        ),
    ]
