# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-06 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Configuracion', '0005_tb_tipoegreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_tipoIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodeIngreso', models.CharField(default='Sin Datos', max_length=30, unique=True)),
                ('dateCreate', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tipo_de_ingreso',
                'managed': True,
            },
        ),
    ]
