# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-27 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameClass', models.CharField(default='Sin Datos', max_length=30, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'clases',
            },
        ),
    ]
