# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-26 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProveedor', models.CharField(default='Sin Datos', max_length=30, null=True)),
                ('razonSocial', models.CharField(default='abc-123', max_length=30, null=True)),
                ('phoneNumberProveedor', models.CharField(default='+000000000', max_length=30, null=True)),
                ('email', models.EmailField(default='sin@datos.com', max_length=30, null=True)),
                ('addressProveedor', models.TextField(default='Sin Datos', null=True)),
                ('dateCreate', models.DateField(auto_now=True)),
            ],
            options={
                'managed': True,
                'db_table': 'proveedores',
            },
        ),
    ]
