# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-16 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUser', models.CharField(default='Sin Definir', max_length=30, null=True)),
                ('mailUser', models.EmailField(default='sin@definir.com', max_length=30, null=True)),
                ('birthdayDate', models.DateField(auto_now_add=True)),
                ('tipoUser', models.CharField(default='Sin Definir', max_length=30, null=True)),
                ('image', models.ImageField(default='', upload_to='users/avatar/' , null=True)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'db_table': 'Profile',
            },
        ),
    ]
