# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-24 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_profile',
            name='dateCreate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='tb_profile',
            table='profile',
        ),
    ]
