# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-27 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20180224_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_profile',
            name='dni',
            field=models.CharField(default='A-000000000', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tb_profile',
            name='houseTlf',
            field=models.CharField(default='+000000000', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tb_profile',
            name='lastName',
            field=models.CharField(default='Sin Definir', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tb_profile',
            name='movilTlf',
            field=models.CharField(default='+000000000', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tb_profile',
            name='tipoUser',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Colaborador', 'Colaborador'), ('SinDefinir', 'Sin Definir'), ('Cliente', 'Cliente'), ('Socio', 'Socio')], default='SinDefinir', max_length=30),
        ),
    ]
