# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-27 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_auto_20180227_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_profile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
