# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-28 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_tb_profile_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_profile',
            name='birthdayDate',
            field=models.DateField(),
        ),
    ]
