# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-01 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_auto_20180228_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_profile',
            name='birthdayDate',
            field=models.DateField(default='1995-04-19', null=True),
        ),
    ]
