# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-12 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0006_auto_20180301_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_profile',
            name='tipoUser',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Colaborador', 'Colaborador'), ('SinDefinir', 'Sin Definir'), ('Socio', 'Socio')], default='SinDefinir', max_length=30),
        ),
    ]
