# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-11 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0007_auto_20180312_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
