# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-06 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0008_auto_20180411_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_profile',
            name='lastName',
            field=models.CharField(default='Sin Definir', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tb_profile',
            name='mailUser',
            field=models.EmailField(default='sin@definir.com', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tb_profile',
            name='nameUser',
            field=models.CharField(default='Sin Definir', max_length=300, null=True),
        ),
    ]
