# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-21 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Configuracion', '0004_auto_20180521_0938'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_colaboradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honorariosPorHora', models.CharField(default='0', max_length=30, null=True)),
                ('diasParaElPremio', models.CharField(default='0', max_length=30, null=True)),
                ('tipoColaborador', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Configuracion.tb_tipoColaborador')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'db_table': 'colaboradores',
            },
        ),
    ]
