# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-21 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_colaboradores',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserProfile.tb_profile'),
        ),
    ]
