# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-07 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0003_auto_20180607_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_colaboradores',
            name='comisionXClase',
            field=models.FloatField(default=0, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tb_colaboradores',
            name='cuentaColaborador',
            field=models.FloatField(default=0, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tb_colaboradores',
            name='honorariosMensuales',
            field=models.FloatField(default=0, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tb_colaboradores',
            name='montoAguinaldo',
            field=models.FloatField(default=0, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tb_colaboradores',
            name='montoXClase',
            field=models.FloatField(default=0, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tb_colaboradores',
            name='presentimo',
            field=models.FloatField(default=0, max_length=300, null=True),
        ),
    ]
