# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-07 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0004_auto_20180607_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_colaboradores',
            name='isMontoXClase',
            field=models.BooleanField(default=False),
        ),
    ]
