# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-08 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0005_tb_colaboradores_ismontoxclase'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_colaboradores',
            name='dateCreate',
            field=models.DateField(auto_now=True),
        ),
    ]
