# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-14 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0006_tb_colaboradores_datecreate'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_cuentaColaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typePago', models.CharField(choices=[('honorariosMensuales', 'Honorarios Mensuales'), ('montoXClase', 'Monto Por clase'), ('SinDefinir', 'Sin Definir'), ('comisionXClase', 'Comision Por Clase'), ('presentimo', 'Presentimo'), ('Aguinaldo', 'Aguinaldo')], default='SinDefinir', max_length=300)),
                ('monto', models.FloatField(default=0, max_length=300, null=True)),
                ('dateCreate', models.DateField(auto_now=True)),
                ('colaborador', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Colaboradores.tb_colaboradores')),
            ],
            options={
                'db_table': 'cuentaColaborador',
                'managed': True,
            },
        ),
    ]
