# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-18 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0007_tb_cuentacolaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_colaboradores',
            name='montoPagadoColaborador',
            field=models.FloatField(default=0, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tb_cuentacolaborador',
            name='typePago',
            field=models.CharField(choices=[('honorarios Mensuales', 'Honorarios Mensuales'), ('Monto Por Clase', 'Monto Por clase'), ('Sin Definir', 'Sin Definir'), ('Comision Por Clase', 'Comision Por Clase'), ('Presentimo', 'Presentimo'), ('Aguinaldo', 'Aguinaldo')], default='SinDefinir', max_length=300),
        ),
    ]
