# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-27 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0009_auto_20180627_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_colaboradores',
            name='isPresentimoPay',
            field=models.BooleanField(default=False),
        ),
    ]
