# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-27 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0010_tb_colaboradores_ispresentimopay'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_EntradaSalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeEntradaSalida', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], default='Entrada', max_length=300)),
                ('dateCreate', models.DateField(auto_now=True)),
                ('colaborador', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Colaboradores.tb_colaboradores')),
            ],
            options={
                'db_table': 'EntradaSalida',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='tb_cuentacolaborador',
            name='typePago',
            field=models.CharField(choices=[('Honorarios Mensuales', 'Honorarios Mensuales'), ('Monto Por Clase', 'Monto Por clase'), ('Sin Definir', 'Sin Definir'), ('Comision Por Clase', 'Comision Por Clase'), ('Presentimo', 'Presentimo'), ('Aguinaldo', 'Aguinaldo'), ('Liquidacion Mensual', 'Liquidacion Mensual')], default='SinDefinir', max_length=300),
        ),
    ]
