# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-01 17:13
from __future__ import unicode_literals

import apps.Colaboradores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0011_auto_20180727_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_entradasalida',
            name='hora',
            field=models.CharField(default=apps.Colaboradores.models.get_default_my_hour, max_length=50),
        ),
    ]
