# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-02 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaboradores', '0012_tb_entradasalida_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_colaboradores',
            name='isHonorariosUpload',
            field=models.BooleanField(default=False),
        ),
    ]
